name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python test_bot.py
    
    - name: Check imports
      run: |
        python -c "import bot; print('✅ bot.py imports successfully')"
        python -c "import database; print('✅ database.py imports successfully')"
        python -c "import course_validator; print('✅ course_validator.py imports successfully')"
        python -c "import telegram_bot; print('✅ telegram_bot.py imports successfully')"

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp *.py deployment/
        cp requirements.txt deployment/
        cp README.md deployment/
        cp .gitignore deployment/
        cp env.example deployment/
    
    - name: Upload deployment artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deployment-package
        path: deployment/

