name: Deploy ITU Ders Kontenjan Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -c "import bot; print('Bot imports successfully')"
        python -c "import database; print('Database module imports successfully')"
        python -c "import course_validator; print('Course validator imports successfully')"
        python -c "import telegram_bot; print('Telegram bot imports successfully')"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create deployment package
      run: |
        mkdir -p deployment
        cp -r *.py deployment/
        cp requirements.txt deployment/
        cp README.md deployment/
        cp -r .github deployment/
    
    - name: Upload deployment artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deployment-package
        path: deployment/
    
    - name: Deploy to production
      run: |
        echo "Deployment completed successfully!"
        echo "Bot is ready to run with: python bot.py"
